apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: helep
data:
  KAFKA_BOOTSTRAP: {{ .Values.global.kafkaBootstrap | quote }}
  SERVICE_PORT: {{ .Values.servicePort | quote }}
  DB_PATH: {{ .Values.dbPath | quote }}
{{- if .Values.matcher }}
  MATCHER: {{ .Values.matcher | quote }}
{{- end }}
