apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sos-triggered
  namespace: helep
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: sos.triggered
  partitions: 3
  replicas: 1
  config:
    retention.ms: "604800000"
