apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: safety-zone-entered
  namespace: kafka
  labels:
    strimzi.io/cluster: helep-kafka
spec:
  topicName: safety.zone.entered
  partitions: 3
  replicas: 1
  config:
    retention.ms: "604800000"
