apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: notification-sent
  namespace: kafka
  labels:
    strimzi.io/cluster: helep-kafka
spec:
  topicName: notification.sent
  partitions: 3
  replicas: 1
  config:
    retention.ms: "604800000"
